### ISSUE TITLE
Do not package the .sass-cache dir

### ISSUE THREAD

**Issue by ChALkeR** [emepyc/tnt.genome#1]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Your 0.0.11 package size is 1.5 MiB packed, **20 MiB** unpacked. 18 MiB of that are inside the `.sass-cache` dir. I suspect that this probably got packed to the release by mistake.

You could put it to `.nmpignore` or remove `.npmignore` completely so npm will ignore everything from `.gitignore` instead.

_Sorry, can't check 0.0.12 atm, but your `.npmignore` is not fixed in the current master._

**Comment by emepyc** [comment]
Yes, thanks for the heads up. This is now fixed (v0.13)
