### ISSUE TITLE
Cannot set the maximum board coordinate using `board.max`

### ISSUE THREAD

**Issue by shusson** [emepyc/tnt.genome#2]
http://tntvis.github.io/tnt.board/api/board/index.html#board.max

Looks like the `max` limit is being overwritten once the board is started in https://github.com/tntvis/tnt.genome/blob/master/src/genome.js#L113

**Comment by emepyc** [comment]
Yes, tnt.genome sets the max coordinate based on the length of the chromosome (not strictly a bug, but a feature). Are you interested in a "boxed" genome view?

**Comment by shusson** [comment]
Yes, I'm considering restricting the region to a gene or a specific area selected by a user.

**Comment by emepyc** [comment]
Ok, I'll take a look and create an example on how to do it

**Comment by shusson** [comment]
hey @emepyc any updates on this?

**Comment by emepyc** [comment]
Sorry for not addressing this before!
Please let me know if this solves your problem:

http://bl.ocks.org/emepyc/9b0cb121ca8d5129b3590704191bd99c
(zoom out until you reach the specified limits)

This change is in version v0.1.6. You can overwrite the limits using min_coord and max_coord. Both accept a Promise

**Comment by shusson** [comment]
Thanks @emepyc, it works great
